name: Check PR description

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-description:
    if: |
      github.event.pull_request.base.ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR description is empty
        run: |
          if [ -z "${{ github.event.pull_request.body }}" ] || [ "${{ github.event.pull_request.body }}" == " " ]; then
            echo "❌ PR must have a description."
            exit 1
          fi

          echo "✅ PR has a description."

      - name: Fail if PR description does not include an issue reference
        run: |
          DESCRIPTION="${{ github.event.pull_request.body }}"

          echo "PR Description:"
          echo "$DESCRIPTION"

          if [[ ! "$DESCRIPTION" =~ (Fixes|Closes|Resolves)\ #[0-9]+ ]]; then
            echo "❌ PR description must include 'Fixes', 'Closes' or 'Resolves' with an issue reference."
            exit 1
          fi

          echo "✅ PR description is valid and contains an issue reference."
