name: Check PR title

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title format
        run: |
          TITLE="${{ github.event.pull_request.title }}"

          echo "PR Title: $TITLE"

          if [[ ! "$TITLE" =~ ^(feat|fix|chore|release|doc): ]]; then
            echo "❌ PR title must start with 'feat:', 'fix:', 'chore:', 'release:' or 'doc:'"
            exit 1
          fi

          echo "✅ PR Title format is valid."
