name: Enforce release branches in Main PRs

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  release-to-main-check:
    if: |
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Valid PR from release/* to main
        run: echo "✅ This PR is from a release/* branch to main."
