name: Require PR Description

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR description is empty
        run: |
          if [ -z "${{ github.event.pull_request.body }}" ] || [ "${{ github.event.pull_request.body }}" == " " ]; then
            echo "❌ PR must have a description."
            exit 1
          else
            echo "✅ PR has a description."
          fi
